export const REQUEST_PARKS='REQUEST_PARKS';
export const GET_PARKS_FAILURE='GET_PARKS_FAILURE';
export const GET_PARKS_SUCCESS='GET_PARKS_SUCCESS';
export const TOGGLE_FORM='TOGGLE_FORM';
export const SELECTED_PARK='SELECTED_PARK';
export const UNSELECT_PARK='UNSELECT_PARK';
export const SHOW_EDIT_FORM='SHOW_EDIT_FORM';
export const HIDE_EDIT_FORM='HIDE_EDIT_FORM';